package report

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/arhuman/prooflog/internal/assess"
	"github.com/arhuman/prooflog/internal/evidence"
)

// AssessModel is the render-ready model for a Tier 0 Evidence Assessment Report
// (ADR-0008). It is a separate model from the continuity ReportModel: an
// assessment carries no attested integrity data, so it must not reuse a document
// type that renders integrity verdicts.
type AssessModel struct {
	Meta    evidence.Meta
	Sources []assess.SourceResult
	// WholeInputDigest binds the entire input (all sources, malformed lines
	// included) to a single SHA-256, printed in the header.
	WholeInputDigest string
	// Malformed is the count of unparseable input lines across the whole input.
	Malformed int
	// Truncated and TruncReason disclose that a size cap stopped the read before
	// end of input, so a truncated assessment can never be mistaken for complete.
	Truncated   bool
	TruncReason string
}

// BuildAssessModel assembles the assessment model from the read Input, forcing
// Tier 0 and the assessment document title regardless of caller-supplied meta
// (REQ-E-14 tier disclosure). The whole-input and per-source digests bind the
// report to exactly the analyzed bytes (REQ-E-15).
func BuildAssessModel(meta evidence.Meta, sources []assess.SourceResult, in *assess.Input) AssessModel {
	meta.Tier = evidence.TierAssessed
	meta.DocumentTitle = "Evidence Assessment Report"
	if meta.Schema == "" {
		meta.Schema = "prooflog.assessment/v1"
	}
	return AssessModel{
		Meta:             meta,
		Sources:          sources,
		WholeInputDigest: in.Digest.Hex(),
		Malformed:        in.Malformed,
		Truncated:        in.Truncated,
		TruncReason:      in.TruncReason,
	}
}

// AssessMarkdown renders a Tier 0 assessment. Its output is deliberately
// unmistakable for a continuity report: a distinct title, a loud non-attestation
// banner, and findings under an "Indicative findings" heading with A-* ids
// (REQ-E-16). It intentionally does not implement the report.Renderer interface:
// its input model (AssessModel) differs from the continuity ReportModel, and the
// two document types must not be interchangeable.
type AssessMarkdown struct{}

// Render implements Renderer-like rendering for the assessment model.
func (AssessMarkdown) Render(m AssessModel) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Prooflog — Evidence Assessment Report\n\n")
	writeAssessBanner(&b)
	writeAssessMeta(&b, m)
	writeAssessTruncation(&b, m)
	writeAssessCoverage(&b, m)
	writeAssessCapabilities(&b, m)
	writeAssessEvents(&b, m)
	writeAssessFindings(&b, m)
	writeAssessInputs(&b, m)
	writeAssessUpgrade(&b)
	return []byte(b.String()), nil
}

func writeAssessBanner(b *strings.Builder) {
	b.WriteString("> **⚠ TIER 0 — ASSESSMENT ONLY. NOTHING BELOW IS CRYPTOGRAPHICALLY ATTESTED.**\n>\n")
	b.WriteString("> This document reports analytical findings over **foreign, unsigned data** " +
		"exported from another tool. Sequence numbers, timestamps, and heartbeats here " +
		"originate from a pipeline Prooflog did not capture and cannot verify. Findings are " +
		"**indicative**: they describe what the export shows, never what can be proven. This is " +
		"not a continuity report and carries no verification certificate. To obtain provable " +
		"evidence, capture with a Prooflog agent (see §Upgrade path).\n\n")
	hr(b)
}

func writeAssessMeta(b *strings.Builder, m AssessModel) {
	meta := m.Meta
	b.WriteString("| | |\n|---|---|\n")
	fmt.Fprintf(b, "| **Report ID** | `%s` |\n", metaOrDash(meta.ReportID))
	fmt.Fprintf(b, "| **Organization** | `%s` |\n", metaOrDash(meta.Org))
	fmt.Fprintf(b, "| **Assurance tier** | %s |\n", meta.Tier.Label())
	fmt.Fprintf(b, "| **Period** | %s → %s |\n", fmtTime(meta.PeriodStart), fmtTime(meta.PeriodEnd))
	fmt.Fprintf(b, "| **Sources assessed** | %s |\n", assessSourceList(m.Sources))
	fmt.Fprintf(b, "| **Generated** | %s |\n", fmtTime(meta.Generated))
	fmt.Fprintf(b, "| **Generated by** | %s |\n", metaOrDash(meta.VerifierName))
	fmt.Fprintf(b, "| **Tool version** | `%s` |\n", metaOrDash(meta.ToolVersion))
	fmt.Fprintf(b, "| **Whole-input digest (SHA-256)** | `%s` |\n", metaOrDash(m.WholeInputDigest))
	fmt.Fprintf(b, "| **Report schema** | `%s` |\n", meta.Schema)
	hr(b)
}

// writeAssessTruncation renders a loud block when a size cap stopped the read
// before end of input, so a partial assessment is never read as complete.
func writeAssessTruncation(b *strings.Builder, m AssessModel) {
	if !m.Truncated {
		return
	}
	b.WriteString("> **⚠ INPUT TRUNCATED — THIS ASSESSMENT IS PARTIAL.**\n>\n")
	fmt.Fprintf(b, "> A size limit stopped the read before the end of the input (%s). "+
		"Records beyond that point were not read and are absent from every count and finding "+
		"below. Re-run without the cap, or narrow the input, for full coverage.\n\n", m.TruncReason)
	hr(b)
}

func writeAssessCoverage(b *strings.Builder, m AssessModel) {
	b.WriteString("## 1. Coverage\n\n")
	b.WriteString("| Source | Records | Observed range | Findings |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, s := range m.Sources {
		fmt.Fprintf(b, "| `%s` | %d | %s → %s | %s |\n",
			s.SourceID, s.Records, assessDate(s.TimeFirst), assessDate(s.TimeLast),
			assessVerdict(s))
	}
	b.WriteString("\n")
	hr(b)
}

// assessVerdict states a per-source, per-tier verdict; assessments never blend
// into a single global pass/fail (ADR-0008).
func assessVerdict(s assess.SourceResult) string {
	if len(s.Findings) == 0 {
		return "no anomalies (Tier 0 — indicative)"
	}
	return fmt.Sprintf("%s (Tier 0 — indicative)", plural(len(s.Findings), "finding"))
}

func writeAssessCapabilities(b *strings.Builder, m AssessModel) {
	b.WriteString("## 2. What this export can and cannot support\n\n")
	b.WriteString("Analyzers run only when the mapped export provides the required signal. " +
		"Analyses listed as *not assessable* were skipped because the export lacks the field — " +
		"not because they passed.\n\n")
	for _, s := range m.Sources {
		fmt.Fprintf(b, "**`%s`.** ", s.SourceID)
		var ran []string
		if s.Caps.Sequenced {
			ran = append(ran, "sequence-gap/duplicate")
		}
		if s.Caps.Heartbeats {
			ran = append(ran, "observation-gap")
		}
		ran = append(ran, "timestamp", "coverage")
		fmt.Fprintf(b, "Assessed: %s. ", strings.Join(ran, ", "))
		if missing := s.Caps.Missing(); len(missing) > 0 {
			fmt.Fprintf(b, "Not assessable on this export: %s.", strings.Join(missing, "; "))
		} else {
			b.WriteString("All Tier 0 analyzers were applicable.")
		}
		b.WriteString("\n\n")
	}
	hr(b)
}

func writeAssessEvents(b *strings.Builder, m AssessModel) {
	b.WriteString("## 3. Events observed (by type)\n\n")
	totals := map[string]int{}
	var order []string
	for _, s := range m.Sources {
		for _, ec := range s.EventCounts {
			if _, seen := totals[ec.Type]; !seen {
				order = append(order, ec.Type)
			}
			totals[ec.Type] += ec.Count
		}
	}
	sort.Strings(order)
	b.WriteString("| Type | Count |\n|---|---|\n")
	if len(order) == 0 {
		b.WriteString("| _(none)_ | 0 |\n")
	}
	for _, t := range order {
		fmt.Fprintf(b, "| `%s` | %d |\n", t, totals[t])
	}
	b.WriteString("\n")
	hr(b)
}

func writeAssessFindings(b *strings.Builder, m AssessModel) {
	b.WriteString("## 4. Indicative findings\n\n")
	b.WriteString("Each finding describes an anomaly **in the export as presented**. None is a " +
		"cryptographic attestation.\n\n")
	n := 0
	for _, s := range m.Sources {
		for _, f := range s.Findings {
			n++
			fmt.Fprintf(b, "**%s — `%s` — %s — severity: %s.** %s",
				f.ID, s.SourceID, f.Title, f.Severity, f.Detail)
			if f.Recommendation != "" {
				fmt.Fprintf(b, " *Recommendation:* %s", f.Recommendation)
			}
			b.WriteString("\n\n")
		}
	}
	if n == 0 {
		b.WriteString("No anomalies detected in the export. This is **not** proof of completeness or " +
			"integrity: an unsigned export can be internally consistent and still be incomplete or " +
			"altered upstream. Only Tier 1+ capture makes completeness provable.\n\n")
	}
	hr(b)
}

func writeAssessInputs(b *strings.Builder, m AssessModel) {
	b.WriteString("## 5. Input attestation\n\n")
	b.WriteString("The assessment is bound to exactly these input bytes. Re-running over the same " +
		"export reproduces these digests; a changed export changes them.\n\n")
	b.WriteString("| Source | Records | Input digest (SHA-256) |\n|---|---|---|\n")
	for _, s := range m.Sources {
		fmt.Fprintf(b, "| `%s` | %d | `%s` |\n", s.SourceID, s.Inputs.RecordCount, s.Inputs.InputDigest)
	}
	if m.Malformed > 0 {
		fmt.Fprintf(b, "\n%d input line(s) could not be parsed; they are excluded from analysis but "+
			"included in the whole-input digest above.\n", m.Malformed)
	}
	b.WriteString("\n")
	hr(b)
}

func writeAssessUpgrade(b *strings.Builder) {
	b.WriteString("## 6. Upgrade path — from assessed to proven\n\n")
	b.WriteString("This report is Tier 0. The assurance ladder:\n\n")
	b.WriteString("- **Tier 0 — assessed (this report).** Analytical findings over an unsigned export.\n")
	b.WriteString("- **Tier 1 — captured.** Record these events through a Prooflog agent: each is " +
		"hashed, sequence-numbered, chained, and sealed. Sequence gaps become *provable*, not indicative.\n")
	b.WriteString("- **Tier 2 — independently verified.** Run the verifier under a separate authority " +
		"from the store operator; history cannot be rewritten undetectably.\n")
	b.WriteString("- **Tier 3 — witnessed.** Add C2SP witness cosigning or a qualified timestamp anchor " +
		"for external, legally-weighted attestation.\n\n")
	b.WriteString("The gaps and blind spots this assessment could only flag as *indicative* become " +
		"cryptographically provable at Tier 1 and above.\n")
}

// --- assessment-local helpers ---

func assessSourceList(sources []assess.SourceResult) string {
	ids := make([]string, 0, len(sources))
	for _, s := range sources {
		ids = append(ids, "`"+s.SourceID+"`")
	}
	if len(ids) == 0 {
		return "—"
	}
	return strings.Join(ids, ", ")
}

func assessDate(t time.Time) string {
	if t.IsZero() {
		return "—"
	}
	return t.UTC().Format("2006-01-02 15:04 UTC")
}
