package report

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/arhuman/prooflog/internal/evidence"
)

// Markdown renders a report model as a Markdown continuity/integrity report,
// the v1 output targeted by examples/continuity-report.md (REQ-E-01, REQ-E-10).
// The optional signature footer is appended by the caller after signing.
type Markdown struct{}

// Render implements Renderer.
func (Markdown) Render(m evidence.ReportModel) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Prooflog — Continuity & Integrity Report\n\n")
	writeMeta(&b, m)
	writeVerdict(&b, m.Sources)
	writeProves(&b)
	writeContinuity(&b, m.Sources)
	writeTransport(&b, m.Sources)
	writeIntegrity(&b, m)
	writeCriticalEvents(&b, m.Sources)
	writePrivacy(&b, m)
	writeFindings(&b, m.Sources)
	writeTrust(&b, m.Meta)
	writeReproduce(&b, m.Meta)
	return []byte(b.String()), nil
}

func hr(b *strings.Builder) { b.WriteString("\n---\n\n") }

func writeMeta(b *strings.Builder, m evidence.ReportModel) {
	meta := m.Meta
	b.WriteString("| | |\n|---|---|\n")
	fmt.Fprintf(b, "| **Report ID** | `%s` |\n", meta.ReportID)
	fmt.Fprintf(b, "| **Organization** | `%s` |\n", meta.Org)
	fmt.Fprintf(b, "| **Period** | %s → %s%s |\n", fmtTime(meta.PeriodStart), fmtTime(meta.PeriodEnd), periodSpan(meta))
	fmt.Fprintf(b, "| **Sources covered** | %s |\n", sourceList(m.Sources))
	fmt.Fprintf(b, "| **Generated** | %s |\n", fmtTime(meta.Generated))
	fmt.Fprintf(b, "| **Generated by** | %s%s |\n", meta.VerifierName, keySuffix(meta.VerifierKeyID))
	fmt.Fprintf(b, "| **Verifier operator** | %s |\n", operatorLine(meta))
	fmt.Fprintf(b, "| **Store locality** | %s |\n", localityLine(meta.StoreLocality))
	fmt.Fprintf(b, "| **Verifier locality** | %s |\n", localityLine(meta.VerifierLocality))
	fmt.Fprintf(b, "| **Tool version** | `%s` |\n", metaOrDash(meta.ToolVersion))
	fmt.Fprintf(b, "| **Verifier binary (SHA-256)** | `%s` |\n", metaOrDash(meta.VerifierBinaryHash))
	fmt.Fprintf(b, "| **Report schema** | `%s` |\n", meta.Schema)
	hr(b)
}

func writeVerdict(b *strings.Builder, sources []evidence.SourceReport) {
	b.WriteString("## 1. Verdict\n\n")
	b.WriteString("| Source | Observability | Event loss | Integrity | Status |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, s := range sources {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n",
			s.SourceID, s.Observability, s.EventLoss, s.Integrity, statusIcon(s.Status))
	}
	b.WriteString("\n**Summary.** ")
	b.WriteString(summary(sources))
	b.WriteString("\n")
	hr(b)
}

// summary states the content-blind verdict in prose, parameterized by the
// per-source transport and observability facts (REQ-E-01).
func summary(sources []evidence.SourceReport) string {
	var b strings.Builder
	b.WriteString("Verified against the records available to the verifier: " +
		"during the period, every event accepted by the local agents was durably " +
		"stored, uploaded, and verified intact: **no accepted event was lost, altered, " +
		"reordered, or removed.**")
	for _, s := range sources {
		if s.Transport.Outages > 0 && s.Transport.ReplayCompleted {
			fmt.Fprintf(&b, " `%s` tolerated %s (longest %s, %d events buffered and fully replayed).",
				s.SourceID, plural(s.Transport.Outages, "network outage"),
				fmtDur(s.Transport.LongestOutage), s.Transport.BufferedEvents)
		}
		for _, w := range s.Windows {
			if w.Bounded {
				continue
			}
			fmt.Fprintf(&b, " `%s` presents an unobserved window of %s; activity there "+
				"**cannot be proven or disproven** by this report (see findings).",
				s.SourceID, fmtDur(w.Duration))
		}
	}
	return b.String()
}

func writeProves(b *strings.Builder) {
	b.WriteString("## 2. What this report proves — and what it does not\n\n")
	b.WriteString("This report is produced from **metadata only**: sequence numbers, hash chains, " +
		"Merkle roots, segment signatures, and heartbeats. Event payloads are encrypted on the " +
		"client before upload; neither the storage operator nor this verification service can read " +
		"them — verification is **content-blind**.\n\n")
	b.WriteString("**Proven, cryptographically:**\n\n")
	b.WriteString("- every event accepted by an agent during the period is present, in order, " +
		"unmodified (hash chain + segment signatures + Merkle roots);\n")
	b.WriteString("- no accepted event was deleted or inserted retroactively (monotonic sequence " +
		"+ chained hashes);\n")
	b.WriteString("- collection continued through network outages without loss (buffered sequence " +
		"ranges match replayed segments);\n")
	b.WriteString("- the periods during which each source was demonstrably alive and able to log " +
		"(signed heartbeats).\n\n")
	b.WriteString("**Not provable, by design — stated honestly:**\n\n")
	b.WriteString("- events an application never emitted cannot be reconstructed;\n")
	b.WriteString("- what happened during an unobserved window (no running agent = no evidence, " +
		"only the boundary of the window is proven);\n")
	b.WriteString("- wall-clock accuracy beyond the monitored clock drift (§5.4);\n")
	b.WriteString("- payload contents (encrypted; verification is content-blind);\n")
	b.WriteString("- **no gap detected ≠ no event was omitted before it reached the agent** — " +
		"guarantees begin at agent acceptance; upstream suppression is invisible by construction;\n")
	hr(b)
}

func writeContinuity(b *strings.Builder, sources []evidence.SourceReport) {
	b.WriteString("## 3. Continuity of observation\n\n")
	if len(sources) > 0 {
		c := sources[0].Continuity
		fmt.Fprintf(b, "Heartbeat policy: interval **%ds**, max allowed silence **%s**.\n\n",
			c.IntervalSeconds, fmtDur(c.MaxSilence))
	}
	b.WriteString("| Source | Expected | Observed | Coverage | Longest gap | Verdict |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, s := range sources {
		fmt.Fprintf(b, "| `%s` | %d | %d | %s | %s | %s |\n",
			s.SourceID, s.Continuity.Expected, s.Continuity.Observed,
			coverage(s.Continuity), fmtDur(s.Continuity.LongestGap),
			boolText(s.Continuity.WithinPolicy, "OK (within policy)", "**GAP — see findings**"))
	}
	b.WriteString("\n")
	writeWindows(b, sources)
	hr(b)
}

func writeWindows(b *strings.Builder, sources []evidence.SourceReport) {
	n := 0
	for _, s := range sources {
		for _, w := range s.Windows {
			if w.Bounded {
				continue
			}
			n++
			fmt.Fprintf(b, "### 3.%d `%s` unobserved window\n\n", n, s.SourceID)
			b.WriteString("```\n")
			fmt.Fprintf(b, "%s   last heartbeat before the gap\n", fmtEvent(w.Start))
			fmt.Fprintf(b, "        ── %s with no running agent: window NOT observed ──\n", fmtDur(w.Duration))
			fmt.Fprintf(b, "%s   observation resumes\n", fmtEvent(w.End))
			b.WriteString("```\n\n")
			b.WriteString("The gap is bounded by heartbeats on both sides and the sequence resumed " +
				"without discontinuity, proving no accepted event was lost. What cannot be proven " +
				"is the absence of unlogged activity on the host during the window.\n\n")
		}
	}
}

func writeTransport(b *strings.Builder, sources []evidence.SourceReport) {
	b.WriteString("## 4. Transport & outage tolerance\n\n")
	b.WriteString("| Source | Outages | Longest | Events buffered | Replay | Loss |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, s := range sources {
		replay := "—"
		if s.Transport.Outages > 0 {
			replay = boolText(s.Transport.ReplayCompleted, "complete", "**incomplete**")
		}
		fmt.Fprintf(b, "| `%s` | %d | %s | %d | %s | %s |\n",
			s.SourceID, s.Transport.Outages, fmtDur(s.Transport.LongestOutage),
			s.Transport.BufferedEvents, replay,
			boolText(s.EventLoss == "None", "none", "**detected**"))
	}
	b.WriteString("\nEvery buffered sequence number was subsequently ACKed by the central store and " +
		"appears in a signed segment. Outages produced zero evidence loss.\n")
	hr(b)
}

func writeIntegrity(b *strings.Builder, m evidence.ReportModel) {
	sources := m.Sources
	b.WriteString("## 5. Integrity\n\n")

	b.WriteString("### 5.1 Sequence continuity\n\n")
	b.WriteString("| Source | Range verified | Gaps | Duplicates | Out-of-order |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, s := range sources {
		fmt.Fprintf(b, "| `%s` | %d → %d | %s | none | none |\n",
			s.SourceID, s.IntegrityData.SeqFirst, s.IntegrityData.SeqLast,
			boolText(!s.IntegrityData.SequenceGaps, "none", "**detected**"))
	}

	b.WriteString("\n### 5.2 Hash chains\n\n")
	b.WriteString("Each `event_hash` matches its recomputed value and each `prev_hash` links to the " +
		"preceding event. Chain heads at period end:\n\n```\n")
	for _, s := range sources {
		fmt.Fprintf(b, "%-16s seq %d  %s\n", s.SourceID, s.IntegrityData.SeqLast, shortHash(s.ChainHead))
	}
	b.WriteString("```\n")

	b.WriteString("\n### 5.3 Segments, signatures, Merkle roots\n\n")
	b.WriteString("| Source | Checkpoints | Signatures valid | Roots match checkpoints |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, s := range sources {
		fmt.Fprintf(b, "| `%s` | %d | %d / %d | %d / %d |\n",
			s.SourceID, s.IntegrityData.CheckpointsTotal,
			s.IntegrityData.CheckpointsValid, s.IntegrityData.CheckpointsTotal,
			s.IntegrityData.CheckpointsValid, s.IntegrityData.CheckpointsTotal)
	}
	b.WriteString("\nCheckpoints were received by this verification service during the period (not " +
		"retroactively), which is what makes after-the-fact rewriting of stored segments detectable.\n\n")
	writeAnchorStatus(b, sources)

	b.WriteString("\n### 5.4 Clock drift\n\n")
	b.WriteString("Max observed drift: ")
	for i, s := range sources {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "`%s` %dms", s.SourceID, s.IntegrityData.MaxClockDriftMS)
	}
	b.WriteString(". Event ordering derives from sequence numbers, not timestamps.\n")

	writeInputs(b, m)
	writeRetention(b, m.Sources)
	hr(b)
}

// writeRetention renders §5.6 when any source has expired segments under the
// retention policy: their ciphertext is deleted but the seq range, Merkle root,
// and signed checkpoints are retained, so the range stays verifiable (WS6).
func writeRetention(b *strings.Builder, sources []evidence.SourceReport) {
	total := 0
	for _, s := range sources {
		total += s.Retention.ExpiredSegments
	}
	if total == 0 {
		return
	}
	b.WriteString("\n### 5.6 Retention\n\n")
	fmt.Fprintf(b, "%s expired under the retention policy during the reporting window. "+
		"Deletion removed the encrypted payloads only; each segment's sequence range, "+
		"Merkle root, and signed checkpoints are retained, so the affected ranges remain "+
		"verifiable-by-commitment and are not reported as gaps.\n\n", plural(total, "segment"))
	b.WriteString("| Source | Expired segments | Ranges | Roots retained |\n|---|---|---|---|\n")
	for _, s := range sources {
		if s.Retention.ExpiredSegments == 0 {
			continue
		}
		ranges := "—"
		if len(s.Retention.ExpiredRanges) > 0 {
			ranges = strings.Join(s.Retention.ExpiredRanges, ", ")
		}
		fmt.Fprintf(b, "| `%s` | %d | %s | %s |\n",
			s.SourceID, s.Retention.ExpiredSegments, ranges,
			boolText(s.Retention.RootsRetained, "yes", "**NO — see findings**"))
	}
}

// writeAnchorStatus renders the §5.3 external-timestamp-anchor line from the
// per-source AnchorSummary, stating anchor coverage with eIDAS honesty: without
// a qualified TSA, anchors prove existence-at-time but carry no Art. 41 legal
// presumption (REQ-C-15).
func writeAnchorStatus(b *strings.Builder, sources []evidence.SourceReport) {
	var total int
	var tsa string
	var latest time.Time
	qualified := true   // AND across configured sources; irrelevant if none configured
	sigVerified := true // AND across configured sources; false until in-process CMS verification exists
	configured := false
	for _, s := range sources {
		if !s.Anchors.Configured {
			continue
		}
		configured = true
		total += s.Anchors.Total
		if s.Anchors.TSA != "" {
			tsa = s.Anchors.TSA
		}
		if s.Anchors.LatestGenTime.After(latest) {
			latest = s.Anchors.LatestGenTime
		}
		if !s.Anchors.Qualified {
			qualified = false
		}
		if !s.Anchors.SignatureVerifiedInProcess {
			sigVerified = false
		}
	}
	if !configured {
		b.WriteString("External timestamp anchor: **not configured** — checkpoint times rest on " +
			"agent clocks and verifier receipt order alone.\n")
		return
	}
	fmt.Fprintf(b, "External timestamp anchor: **%s** from `%s` (latest genTime %s); each receipt "+
		"binds a checkpoint's exact bytes to an externally attested time.\n",
		plural(total, "anchor receipt"), tsa, fmtTime(latest))
	if !sigVerified {
		// State only what is proven in-process: imprint + nonce, not the token
		// signature. The whole DER token is stored for external checking (REQ-C-15).
		b.WriteString("Verification scope: each receipt's SHA-256 imprint and nonce round-trip are " +
			"checked in-process; the TSA token's CMS signature is **not** verified in-process — " +
			"verify externally with `openssl ts -verify`.\n")
	}
	if !qualified {
		b.WriteString("The TSA is not eIDAS-qualified: anchors prove existence-at-time but carry no " +
			"Art. 41 legal presumption.\n")
	}
}

// writeInputs renders §5.5, attesting the exact evidence each source verdict was
// computed from (record count, input digest, accepted checkpoint ids) and the
// algorithm identities used, each citable to its standard (REQ-E-02).
func writeInputs(b *strings.Builder, m evidence.ReportModel) {
	b.WriteString("\n### 5.5 Inputs & algorithms\n\n")
	b.WriteString("This report was computed from exactly the following evidence. The input digest " +
		"is a SHA-256 over the ordered per-record hashes; recomputing it over the same records " +
		"reproduces this value.\n\n")
	b.WriteString("| Source | Records | Input digest (SHA-256) | Checkpoints |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, s := range m.Sources {
		fmt.Fprintf(b, "| `%s` | %d | `%s` | %s |\n",
			s.SourceID, s.Inputs.RecordCount, s.Inputs.InputDigest, checkpointList(s.Inputs.CheckpointIDs))
	}
	if len(m.Meta.Algorithms) > 0 {
		b.WriteString("\nAlgorithm identities used:\n\n")
		for _, alg := range m.Meta.Algorithms {
			fmt.Fprintf(b, "- %s\n", alg)
		}
	}
}

// checkpointList renders the accepted checkpoint ids of a source for §5.5.
func checkpointList(ids []string) string {
	if len(ids) == 0 {
		return "—"
	}
	quoted := make([]string, 0, len(ids))
	for _, id := range ids {
		quoted = append(quoted, "`"+id+"`")
	}
	return strings.Join(quoted, "; ")
}

func writeCriticalEvents(b *strings.Builder, sources []evidence.SourceReport) {
	b.WriteString("## 6. Critical events recorded (evidence summary)\n\n")
	b.WriteString("Payloads are encrypted; the counts below come from visible envelope metadata " +
		"(`event_type`).\n\n")
	b.WriteString("| Type | Count |\n|---|---|\n")
	totals := map[string]int{}
	var order []string
	for _, s := range sources {
		for _, ec := range s.EventCounts {
			if _, seen := totals[ec.Type]; !seen {
				order = append(order, ec.Type)
			}
			totals[ec.Type] += ec.Count
		}
	}
	sort.Strings(order)
	if len(order) == 0 {
		b.WriteString("| _(no non-heartbeat events recorded)_ | 0 |\n")
	}
	for _, t := range order {
		fmt.Fprintf(b, "| `%s` | %d |\n", t, totals[t])
	}
	hr(b)
}

// writePrivacy renders §7, the Privacy manifest: a field-by-field disclosure
// table (what is plaintext, pseudonymous, or encrypted) plus the
// pseudonymization scheme and payload-erasure granularity (WS4, REQ-C-03/08).
func writePrivacy(b *strings.Builder, m evidence.ReportModel) {
	b.WriteString("## 7. Privacy manifest\n\n")
	keyID := ""
	for _, s := range m.Sources {
		if keyID == "" && s.KeyID != "" {
			keyID = s.KeyID
		}
	}
	if keyID == "" {
		keyID = "not configured"
	}
	b.WriteString("Each envelope field's disclosure level:\n\n")
	b.WriteString("| Field | Disclosure |\n|---|---|\n")
	b.WriteString("| `source_id` | plaintext (infrastructure identity) |\n")
	b.WriteString("| `seq` | plaintext |\n")
	b.WriteString("| `event_type` | plaintext |\n")
	b.WriteString("| `event_time` / `ingest_time` | plaintext |\n")
	b.WriteString("| `outcome` | plaintext (closed enum: success, failure, denied, unknown, empty) |\n")
	b.WriteString("| `actor` | pseudonymous (HMAC-SHA256, per-subject erasable salt) |\n")
	b.WriteString("| `payload`, labels | encrypted (age, organization key) |\n\n")
	b.WriteString("**Pseudonymization scheme.** Actors are HMAC-SHA256 with a per-subject 256-bit salt " +
		"held only on the source host; erasing a salt severs linkability without rewriting records. " +
		"The hash chain stays verifiable without any salt — pseudonyms live inside the hashed bytes.\n\n")
	fmt.Fprintf(b, "**Payload erasure granularity.** Payloads (and the labels folded into them) are "+
		"encrypted to the organization key `%s`; per-subject payload keys are planned.\n\n", keyID)
	b.WriteString("| Property | Status |\n|---|---|\n")
	b.WriteString("| Central store can decrypt payloads | no |\n")
	b.WriteString("| This verification service can decrypt payloads | no |\n")
	fmt.Fprintf(b, "| Decryption key holder | organization `%s` only (X25519) |\n", keyID)
	hr(b)
}

func writeFindings(b *strings.Builder, sources []evidence.SourceReport) {
	b.WriteString("## 8. Findings\n\n")
	n := 0
	for _, s := range sources {
		for _, f := range s.Findings {
			n++
			fmt.Fprintf(b, "**F-%d — %s — severity: %s.** %s", n, f.Title, f.Severity, f.Detail)
			if f.Recommendation != "" {
				fmt.Fprintf(b, " *Recommendation:* %s", f.Recommendation)
			}
			b.WriteString("\n\n")
		}
	}
	if n == 0 {
		b.WriteString("No findings. Integrity and continuity checks passed on all sources.\n")
	}
	hr(b)
}

func writeTrust(b *strings.Builder, meta evidence.Meta) {
	b.WriteString("## 9. Trust assumptions & limitations\n\n")
	b.WriteString("This report is trustworthy under the following assumptions, stated explicitly:\n\n")
	if meta.SelfHosted {
		b.WriteString("1. **Verifier independence — NOT satisfied.** This report was generated by a " +
			"self-hosted verifier operated by the same organization that runs the store. The v1 " +
			"separation of powers does not hold here: an operator controlling agents, store, **and** " +
			"verifier could rewrite history undetectably. This is stated per the honest threat model " +
			"(decisions.md).\n")
	} else {
		fmt.Fprintf(b, "1. **Verifier independence.** This report was generated by a verification "+
			"service operated by %s, independent from the operator of the central store. Rewriting "+
			"stored history without detection would require compromising the agents, the store, "+
			"**and** this service.\n", meta.VerifierOperator)
	}
	b.WriteString("2. **Agent key integrity.** Events are signed with per-agent keys held on the " +
		"source hosts. An attacker holding an agent's key could forge *new* events from that source " +
		"(never rewrite anchored past ones). No key revocation events were recorded during the period.\n")
	b.WriteString("3. **Coverage boundary.** Prooflog proves the integrity and continuity of " +
		"*accepted* events. It does not observe the host beyond what agents emit, and it is not a " +
		"legal guarantee of compliance.\n")
	if meta.StoreLocality == "" || meta.VerifierLocality == "" {
		b.WriteString("4. **Data residency.** Component locality was not (fully) declared by the " +
			"operator; data-residency posture cannot be assessed from this report (see " +
			"docs/data_residency.md).\n")
	} else {
		b.WriteString("4. **Data residency.** Store and verifier localities are operator " +
			"declarations recorded for chain of custody; they are not cryptographically proven.\n")
	}
	hr(b)
}

func writeReproduce(b *strings.Builder, meta evidence.Meta) {
	b.WriteString("## 10. Reproduce this verification\n\n")
	if meta.Reproduce == "" {
		b.WriteString("Reproduce command: **not configured** (re-run `prooflog verify` against the " +
			"same spool/bundle and checkpoints).\n")
		return
	}
	b.WriteString("This report is independently reproducible offline from the evidence, without " +
		"contacting the verifier operator:\n\n```bash\n")
	b.WriteString(meta.Reproduce)
	b.WriteString("\n```\n\nThe verification recomputes every hash chain, Merkle root, and signature " +
		"above. Decrypting payloads additionally requires the organization's key and is not needed " +
		"for any check in this report.\n")
}

// --- small formatting helpers ---

func sourceList(sources []evidence.SourceReport) string {
	ids := make([]string, 0, len(sources))
	for _, s := range sources {
		ids = append(ids, "`"+s.SourceID+"`")
	}
	if len(ids) == 0 {
		return "—"
	}
	return strings.Join(ids, ", ")
}

func metaOrDash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

// localityLine renders an operator-declared jurisdiction, marking it explicitly
// as a declaration (not a proof) or as undeclared (data_residency.md).
func localityLine(v string) string {
	if v == "" {
		return "— (not declared)"
	}
	return v + " (declared by operator; not proven)"
}

func operatorLine(meta evidence.Meta) string {
	if meta.SelfHosted {
		return "self-hosted — **not independent** from the storage operator (see §9)"
	}
	return meta.VerifierOperator + " — independent from the storage operator"
}

func keySuffix(keyID string) string {
	if keyID == "" {
		return ""
	}
	return " (key `" + keyID + "`)"
}

func periodSpan(meta evidence.Meta) string {
	if meta.PeriodStart.IsZero() || meta.PeriodEnd.IsZero() {
		return ""
	}
	d := meta.PeriodEnd.Sub(meta.PeriodStart)
	if d <= 0 {
		return ""
	}
	if d >= time.Hour {
		return fmt.Sprintf(" (%dh)", int(d.Round(time.Hour)/time.Hour))
	}
	return " (" + fmtDur(d) + ")"
}

func coverage(c evidence.ContinuitySummary) string {
	if c.Expected <= 0 {
		return "—"
	}
	pct := float64(c.Observed) / float64(c.Expected) * 100
	if pct > 100 {
		pct = 100
	}
	return strconv.FormatFloat(pct, 'f', 2, 64) + " %"
}

func shortHash(h string) string {
	if len(h) <= 8 {
		return h
	}
	return h[:4] + "…" + h[len(h)-4:]
}

func fmtEvent(t time.Time) string {
	if t.IsZero() {
		return "(unknown time)"
	}
	return t.UTC().Format("2006-01-02 15:04:05 UTC")
}

func statusIcon(status string) string {
	switch status {
	case "OK":
		return "OK"
	case "ATTENTION":
		return "ATTENTION"
	case "FAIL":
		return "FAIL"
	default:
		return status
	}
}

func fmtTime(t time.Time) string {
	if t.IsZero() {
		return "—"
	}
	return t.UTC().Format("2006-01-02 15:04:05 UTC")
}

func fmtDur(d time.Duration) string {
	if d == 0 {
		return "—"
	}
	d = d.Round(time.Second)
	m := int(d / time.Minute)
	s := int((d % time.Minute) / time.Second)
	if m == 0 {
		return strconv.Itoa(s) + "s"
	}
	return strconv.Itoa(m) + "m" + fmt.Sprintf("%02d", s) + "s"
}

func plural(n int, unit string) string {
	if n == 1 {
		return "1 " + unit
	}
	return strconv.Itoa(n) + " " + unit + "s"
}
