// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: proto/prooflog/v1/prooflog.proto

package prooflogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreService_UploadSegment_FullMethodName    = "/prooflog.v1.StoreService/UploadSegment"
	StoreService_PullSegments_FullMethodName     = "/prooflog.v1.StoreService/PullSegments"
	StoreService_SubmitCheckpoint_FullMethodName = "/prooflog.v1.StoreService/SubmitCheckpoint"
	StoreService_PlaceHold_FullMethodName        = "/prooflog.v1.StoreService/PlaceHold"
	StoreService_ReleaseHold_FullMethodName      = "/prooflog.v1.StoreService/ReleaseHold"
	StoreService_ListHolds_FullMethodName        = "/prooflog.v1.StoreService/ListHolds"
	StoreService_ListTombstones_FullMethodName   = "/prooflog.v1.StoreService/ListTombstones"
)

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StoreService is the central store: it accepts uploaded segments, serves
// stored frames to the verifier, and opportunistically forwards checkpoints.
type StoreServiceClient interface {
	// UploadSegment streams a segment (meta header then frames) and returns an
	// ack only after the blob is fsynced and the index committed (REQ-E-04).
	UploadSegment(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, SegmentAck], error)
	// PullSegments streams back the exact stored frames of a source from a seq.
	PullSegments(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error)
	// SubmitCheckpoint records a checkpoint the store may forward to the verifier.
	SubmitCheckpoint(ctx context.Context, in *SignedNote, opts ...grpc.CallOption) (*CheckpointAck, error)
	// PlaceHold places a legal hold exempting a source (or range) from deletion.
	PlaceHold(ctx context.Context, in *PlaceHoldRequest, opts ...grpc.CallOption) (*Hold, error)
	// ReleaseHold releases a previously placed legal hold.
	ReleaseHold(ctx context.Context, in *ReleaseHoldRequest, opts ...grpc.CallOption) (*Hold, error)
	// ListHolds lists legal holds, optionally filtered to one source.
	ListHolds(ctx context.Context, in *ListHoldsRequest, opts ...grpc.CallOption) (*ListHoldsResponse, error)
	// ListTombstones lists segments deleted under retention (blob gone, row kept).
	ListTombstones(ctx context.Context, in *ListTombstonesRequest, opts ...grpc.CallOption) (*ListTombstonesResponse, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) UploadSegment(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, SegmentAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[0], StoreService_UploadSegment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadRequest, SegmentAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_UploadSegmentClient = grpc.ClientStreamingClient[UploadRequest, SegmentAck]

func (c *storeServiceClient) PullSegments(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[1], StoreService_PullSegments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullRequest, Frame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_PullSegmentsClient = grpc.ServerStreamingClient[Frame]

func (c *storeServiceClient) SubmitCheckpoint(ctx context.Context, in *SignedNote, opts ...grpc.CallOption) (*CheckpointAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointAck)
	err := c.cc.Invoke(ctx, StoreService_SubmitCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) PlaceHold(ctx context.Context, in *PlaceHoldRequest, opts ...grpc.CallOption) (*Hold, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hold)
	err := c.cc.Invoke(ctx, StoreService_PlaceHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ReleaseHold(ctx context.Context, in *ReleaseHoldRequest, opts ...grpc.CallOption) (*Hold, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hold)
	err := c.cc.Invoke(ctx, StoreService_ReleaseHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListHolds(ctx context.Context, in *ListHoldsRequest, opts ...grpc.CallOption) (*ListHoldsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHoldsResponse)
	err := c.cc.Invoke(ctx, StoreService_ListHolds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) ListTombstones(ctx context.Context, in *ListTombstonesRequest, opts ...grpc.CallOption) (*ListTombstonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTombstonesResponse)
	err := c.cc.Invoke(ctx, StoreService_ListTombstones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility.
//
// StoreService is the central store: it accepts uploaded segments, serves
// stored frames to the verifier, and opportunistically forwards checkpoints.
type StoreServiceServer interface {
	// UploadSegment streams a segment (meta header then frames) and returns an
	// ack only after the blob is fsynced and the index committed (REQ-E-04).
	UploadSegment(grpc.ClientStreamingServer[UploadRequest, SegmentAck]) error
	// PullSegments streams back the exact stored frames of a source from a seq.
	PullSegments(*PullRequest, grpc.ServerStreamingServer[Frame]) error
	// SubmitCheckpoint records a checkpoint the store may forward to the verifier.
	SubmitCheckpoint(context.Context, *SignedNote) (*CheckpointAck, error)
	// PlaceHold places a legal hold exempting a source (or range) from deletion.
	PlaceHold(context.Context, *PlaceHoldRequest) (*Hold, error)
	// ReleaseHold releases a previously placed legal hold.
	ReleaseHold(context.Context, *ReleaseHoldRequest) (*Hold, error)
	// ListHolds lists legal holds, optionally filtered to one source.
	ListHolds(context.Context, *ListHoldsRequest) (*ListHoldsResponse, error)
	// ListTombstones lists segments deleted under retention (blob gone, row kept).
	ListTombstones(context.Context, *ListTombstonesRequest) (*ListTombstonesResponse, error)
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServiceServer struct{}

func (UnimplementedStoreServiceServer) UploadSegment(grpc.ClientStreamingServer[UploadRequest, SegmentAck]) error {
	return status.Error(codes.Unimplemented, "method UploadSegment not implemented")
}
func (UnimplementedStoreServiceServer) PullSegments(*PullRequest, grpc.ServerStreamingServer[Frame]) error {
	return status.Error(codes.Unimplemented, "method PullSegments not implemented")
}
func (UnimplementedStoreServiceServer) SubmitCheckpoint(context.Context, *SignedNote) (*CheckpointAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCheckpoint not implemented")
}
func (UnimplementedStoreServiceServer) PlaceHold(context.Context, *PlaceHoldRequest) (*Hold, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceHold not implemented")
}
func (UnimplementedStoreServiceServer) ReleaseHold(context.Context, *ReleaseHoldRequest) (*Hold, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseHold not implemented")
}
func (UnimplementedStoreServiceServer) ListHolds(context.Context, *ListHoldsRequest) (*ListHoldsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHolds not implemented")
}
func (UnimplementedStoreServiceServer) ListTombstones(context.Context, *ListTombstonesRequest) (*ListTombstonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTombstones not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}
func (UnimplementedStoreServiceServer) testEmbeddedByValue()                      {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	// If the following call panics, it indicates UnimplementedStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_UploadSegment_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServiceServer).UploadSegment(&grpc.GenericServerStream[UploadRequest, SegmentAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_UploadSegmentServer = grpc.ClientStreamingServer[UploadRequest, SegmentAck]

func _StoreService_PullSegments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServiceServer).PullSegments(m, &grpc.GenericServerStream[PullRequest, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_PullSegmentsServer = grpc.ServerStreamingServer[Frame]

func _StoreService_SubmitCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedNote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).SubmitCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_SubmitCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).SubmitCheckpoint(ctx, req.(*SignedNote))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_PlaceHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).PlaceHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_PlaceHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).PlaceHold(ctx, req.(*PlaceHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ReleaseHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ReleaseHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ReleaseHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ReleaseHold(ctx, req.(*ReleaseHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListHolds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHoldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListHolds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListHolds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListHolds(ctx, req.(*ListHoldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_ListTombstones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTombstonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).ListTombstones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_ListTombstones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).ListTombstones(ctx, req.(*ListTombstonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prooflog.v1.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitCheckpoint",
			Handler:    _StoreService_SubmitCheckpoint_Handler,
		},
		{
			MethodName: "PlaceHold",
			Handler:    _StoreService_PlaceHold_Handler,
		},
		{
			MethodName: "ReleaseHold",
			Handler:    _StoreService_ReleaseHold_Handler,
		},
		{
			MethodName: "ListHolds",
			Handler:    _StoreService_ListHolds_Handler,
		},
		{
			MethodName: "ListTombstones",
			Handler:    _StoreService_ListTombstones_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadSegment",
			Handler:       _StoreService_UploadSegment_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PullSegments",
			Handler:       _StoreService_PullSegments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/prooflog/v1/prooflog.proto",
}

const (
	VerifierService_SubmitCheckpoint_FullMethodName = "/prooflog.v1.VerifierService/SubmitCheckpoint"
)

// VerifierServiceClient is the client API for VerifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VerifierService receives checkpoints directly from agents so they survive a
// store compromise (REQ-C-07).
type VerifierServiceClient interface {
	SubmitCheckpoint(ctx context.Context, in *SignedNote, opts ...grpc.CallOption) (*CheckpointAck, error)
}

type verifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifierServiceClient(cc grpc.ClientConnInterface) VerifierServiceClient {
	return &verifierServiceClient{cc}
}

func (c *verifierServiceClient) SubmitCheckpoint(ctx context.Context, in *SignedNote, opts ...grpc.CallOption) (*CheckpointAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointAck)
	err := c.cc.Invoke(ctx, VerifierService_SubmitCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifierServiceServer is the server API for VerifierService service.
// All implementations must embed UnimplementedVerifierServiceServer
// for forward compatibility.
//
// VerifierService receives checkpoints directly from agents so they survive a
// store compromise (REQ-C-07).
type VerifierServiceServer interface {
	SubmitCheckpoint(context.Context, *SignedNote) (*CheckpointAck, error)
	mustEmbedUnimplementedVerifierServiceServer()
}

// UnimplementedVerifierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerifierServiceServer struct{}

func (UnimplementedVerifierServiceServer) SubmitCheckpoint(context.Context, *SignedNote) (*CheckpointAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCheckpoint not implemented")
}
func (UnimplementedVerifierServiceServer) mustEmbedUnimplementedVerifierServiceServer() {}
func (UnimplementedVerifierServiceServer) testEmbeddedByValue()                         {}

// UnsafeVerifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifierServiceServer will
// result in compilation errors.
type UnsafeVerifierServiceServer interface {
	mustEmbedUnimplementedVerifierServiceServer()
}

func RegisterVerifierServiceServer(s grpc.ServiceRegistrar, srv VerifierServiceServer) {
	// If the following call panics, it indicates UnimplementedVerifierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerifierService_ServiceDesc, srv)
}

func _VerifierService_SubmitCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedNote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServiceServer).SubmitCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifierService_SubmitCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServiceServer).SubmitCheckpoint(ctx, req.(*SignedNote))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifierService_ServiceDesc is the grpc.ServiceDesc for VerifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prooflog.v1.VerifierService",
	HandlerType: (*VerifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitCheckpoint",
			Handler:    _VerifierService_SubmitCheckpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/prooflog/v1/prooflog.proto",
}
